# SPDX-License-Identifier: Apache-2.0
name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: lpasquali/rune-ci/.github/workflows/python-publish.yml@main
    with:
      pypi-project: "rune-bench"
      tag-docs: true
    secrets:
      RUNE_CHARTS_BOT_TOKEN: ${{ secrets.RUNE_CHARTS_BOT_TOKEN }}
